apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-worker-country
  namespace: wimyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apex-worker-country
  template:
    metadata:
      labels:
        app: apex-worker-country
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: apex-worker-country
          image: ghcr.io/onurkayakiran/wimyip-backend:latest
          command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info", "-Q", "apex-country", "--concurrency=1"]
          envFrom:
            - configMapRef:
                name: wimyip-config
            - secretRef:
                name: wimyip-secrets
