apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wimyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/onurkayakiran/wimyip-backend:181da1d1df36d6a88fa06d177e2b0c8d0c57353f
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: wimyip-config
            - secretRef:
                name: wimyip-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wimyip
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
