apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat
  namespace: wimyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: beat
          image: ghcr.io/onurkayakiran/wimyip-backend:cb1a4c8f2d6e1015c79cee4544f0ccacf8bca9d7
          command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=info"]
          envFrom:
            - configMapRef:
                name: wimyip-config
            - secretRef:
                name: wimyip-secrets
