apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptr-worker
  namespace: wimyip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptr-worker
  template:
    metadata:
      labels:
        app: ptr-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ptr-worker
          image: ghcr.io/onurkayakiran/wimyip-backend:cb1a4c8f2d6e1015c79cee4544f0ccacf8bca9d7
          command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=info", "-Q", "ptr", "--concurrency=1"]
          envFrom:
            - configMapRef:
                name: wimyip-config
            - secretRef:
                name: wimyip-secrets
